# Generated by Django 5.0.14 on 2026-02-14 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_prescriptions',
            field=models.TextField(blank=True, help_text='Current medications and prescriptions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated 3-bullet CliffNotes summary'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='recommended_action',
            field=models.CharField(blank=True, help_text='AI-recommended next step for the doctor', max_length=255),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('patient', 'Patient')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='triage.triagesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
