# Generated by Django 5.0.14 on 2026-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_patient_current_prescriptions_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesession',
            name='thread_id',
            field=models.CharField(blank=True, help_text='Azure AI thread ID for persistence', max_length=255, null=True),
        ),
    ]
