# Generated by Django 5.0.14 on 2026-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_triagesession_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesession',
            name='active_agent_role',
            field=models.CharField(default='intake', help_text='The role of the agent currently handling this session (e.g., intake, analysis, guardian)', max_length=50),
        ),
    ]
