# Generated by Django 5.0.14 on 2026-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_triagesession_active_agent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagesession',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='urgency_score',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
